### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by kaesrel** [ZEZAY/real-estate-rental#14]
This is an **EMERGENCY ISSUE!!!**.
This has to be done **TODAY!!!**

**Comment by kaesrel** [comment]
I am working on pipenv method right now.
It is working fine for now, but let me make sure that it really works.

**Comment by kaesrel** [comment]
**I have finished it!!!**:satisfied:
Wasted like 3 hours on pipenv. It works well on WSL, but fails on anaconda prompt and windows cmd. :cold_sweat:
I switched to use normal virtualenv. Alas, it works on both terminals. :triumph:
Please take a look at it.

**Comment by Sahadporn** [comment]
It work on my laptop both window and Mac.

**Comment by GifperTC** [comment]
Is this completely finished? If it is then I will close this issue.

**Comment by GifperTC** [comment]
- [ ] Proof read texts
- [ ] Adjust code part
