### ISSUE TITLE
[WINDOW]NameError when creating a new unit that assigned to an existing condo

### ISSUE THREAD

**Issue by bleachjade** [ZEZAY/real-estate-rental#22]
After I've created an account for myself, I created a test condo with one image, and then I tried to add a unit to the condo but I shown an error when I click the upload button.

![image](https://user-images.githubusercontent.com/46812243/100496008-35526080-3183-11eb-9df1-ff3358b67420.png)

**Comment by ZEZAY** [comment]
THANK YOU for the report,
The problem has already been sliven.
