### ISSUE TITLE
Design suggestion and some HTML/CSS bug

### ISSUE THREAD

**Issue by bleachjade** [ZEZAY/real-estate-rental#23]
- the logo image is not displayed properly
![image](https://user-images.githubusercontent.com/46812243/100496124-3afc7600-3184-11eb-88ab-73c9c02d0e06.png)
-  also the logo at the footer page
![image](https://user-images.githubusercontent.com/46812243/100496133-54052700-3184-11eb-8da1-436927783ec2.png)

- the condo description container is not well-wrap
![image](https://user-images.githubusercontent.com/46812243/100496162-8151d500-3184-11eb-8538-ab1623cb0572.png)

- I don't understand what the property realtor gonna help me with on this page, is it just a mockup, or I can click a link to a real one? maybe in the future of the app?
- also the **Make An Inquiry** button should respond to some feedback when I click it according to the [Interaction Design Principle](https://givegoodux.com/feedback-5-principles-interaction-design-supercharge-ui-5-5/#:~:text=Principle%205%3A%20Good%20Interaction%20Design,failed%20at%20performing%20a%20task.&text=That%27s%20feedback%2C%20telling%20you%20that%20the%20item%20is%20clickable.)
![image](https://user-images.githubusercontent.com/46812243/100496254-253b8080-3185-11eb-8ad6-d8d5ca693c3a.png)

- This *Username* button did not redirect me anywhere
![image](https://user-images.githubusercontent.com/46812243/100496346-ed810880-3185-11eb-86d8-4ed74ebba153.png)

- not quite understand what this section does. At first, I think if I'm the one who creates the condo post then I can manage the information like is it near the BTS but when I log-in into another account that not the owner one, I still can edit this section? so I not sure what this section does
![image](https://user-images.githubusercontent.com/46812243/100496358-130e1200-3186-11eb-9760-1c0db3db6fb7.png)

**Comment by ZEZAY** [comment]
At the last topic, it is not a bug that visitors can edit the section. It is a search filter for map API that visitors could find the BTS station near the condo.
Thank you for the report, we will fix it ASAP!

**Comment by ZEZAY** [comment]
Done!
