### ISSUE TITLE
Oauth and style error

### ISSUE THREAD

**Issue by BenZacs** [ZEZAY/real-estate-rental#25]
When I click in the Google button that lead me to the google Oauth it show this page:
![Screenshot from 2020-11-29 21-26-10](https://user-images.githubusercontent.com/48821759/100544698-0a066900-328a-11eb-8165-7cd60bb24e80.png)
but normal sign up is work correctly.
In all page have logo picture with this picture:
![Screenshot from 2020-11-29 21-11-05](https://user-images.githubusercontent.com/48821759/100544853-366eb500-328b-11eb-9d00-b5bcc362c4a7.png)
![Screenshot from 2020-11-29 21-11-24](https://user-images.githubusercontent.com/48821759/100544864-4090b380-328b-11eb-97c6-650e78b0dd8a.png)
![Screenshot from 2020-11-29 21-12-59](https://user-images.githubusercontent.com/48821759/100544875-53a38380-328b-11eb-82cb-4a7e7183d8bd.png)
![Screenshot from 2020-11-29 21-13-03](https://user-images.githubusercontent.com/48821759/100544880-5dc58200-328b-11eb-9220-800d38b5151d.png)

**Comment by ZEZAY** [comment]
Thank you for the report.
UI is all set now. We will fix Oauth ASAP.

**Comment by kaesrel** [comment]
We fixed it already.
