### ISSUE TITLE
For create condo

### ISSUE THREAD

**Issue by BenZacs** [ZEZAY/real-estate-rental#26]
When I add another image, the previous image is disappear and I have to add it again:
![Screenshot from 2020-11-29 22-00-18](https://user-images.githubusercontent.com/48821759/100545433-594e9880-328e-11eb-9bfd-a3f8448f2df3.png)
![Screenshot from 2020-11-29 22-00-21](https://user-images.githubusercontent.com/48821759/100545436-5b185c00-328e-11eb-807d-56177970af7b.png)
 and when I click the upload button it show:
![Screenshot from 2020-11-29 22-01-56](https://user-images.githubusercontent.com/48821759/100545485-987ce980-328e-11eb-800e-1d11068dac3e.png)
So, it mean you do not have image field in the condo's model
and have the same problem in unit.
When i return to index page it still show this:
![Screenshot from 2020-11-29 22-12-55](https://user-images.githubusercontent.com/48821759/100545776-1e4d6480-3290-11eb-9729-1a97d3d4fbe3.png)

**Comment by ZEZAY** [comment]
THANK YOU for the report,
The problem has already been sliven.
