### ISSUE TITLE
Some picture and formatting problems

### ISSUE THREAD

**Issue by jeanyjean** [ZEZAY/real-estate-rental#28]
URL : http://akezurel.pythonanywhere.com/estate/condo/4/

1. The logo on the navigation bar and footer are not loaded in. The picture for the condo itself is also not loaded in.
![Capture](https://user-images.githubusercontent.com/59855893/100898485-65875f80-34f3-11eb-9feb-96003f4e1369.PNG)
![image](https://user-images.githubusercontent.com/59855893/100898552-759f3f00-34f3-11eb-874f-a862ce4eb29e.png)

2. My username got cutoff by the "logout" button.
![image](https://user-images.githubusercontent.com/59855893/100899528-8a300700-34f4-11eb-9ce6-cb6ac1ca2247.png)

3. Each page only show one result? Maybe you should show at least 3 with the space available.
![image](https://user-images.githubusercontent.com/59855893/100899759-bfd4f000-34f4-11eb-8e34-7b23719e71cc.png)

How to reproduce:
1. Click "Condo" on the navigation bar above.
2. Click "The city condo" box at the bottom.

**Comment by ZEZAY** [comment]
Thank you for the report, we did fix it all!
