### ISSUE TITLE
Got an error page when creating condo.

### ISSUE THREAD

**Issue by jeanyjean** [ZEZAY/real-estate-rental#29]
URL : http://akezurel.pythonanywhere.com/estate/

I got an error page as shown below, when trying to create a condo without uploading a picture.
Maybe I should get redirect to the same page telling me to input image or don't allow me to post without image instead.

![image](https://user-images.githubusercontent.com/59855893/100900869-de87b680-34f5-11eb-850d-dbf2e12c5531.png)

How to reproduce:
1. Login with owner account type.
2. Click "Post" on the navigation bar on the right side.
3. Input everything except uploading the image.
4. Click "upload" button

**Comment by ZEZAY** [comment]
THANK YOU for the report,
The problem has already been sliven.
