### ISSUE TITLE
Can't access the website

### ISSUE THREAD

**Issue by jeanyjean** [ZEZAY/real-estate-rental#30]
URL : http://akezurel.pythonanywhere.com/

I can't access the website anymore.
![image](https://user-images.githubusercontent.com/59855893/100920672-0aaf3180-350e-11eb-8567-c7626f11999a.png)

How to reproduce:
1. Try to access the link http://akezurel.pythonanywhere.com/

**Comment by ZEZAY** [comment]
THANK YOU for the report,
The problem has already been sliven.
