### ISSUE TITLE
Functionality Error when posting a new condo

### ISSUE THREAD

**Issue by bleachjade** [ZEZAY/real-estate-rental#31]
When I click upload condo at the uploading condo page it throws an error
- http://akezurel.pythonanywhere.com/estate/upload/condo/

![image](https://user-images.githubusercontent.com/46812243/100973100-80e28100-356c-11eb-9df3-2f5201dcfba8.png)

also, this is the information I filled in:

![image](https://user-images.githubusercontent.com/46812243/100973225-c141ff00-356c-11eb-9ee4-b7558aa93d58.png)
![image](https://user-images.githubusercontent.com/46812243/100973258-d0c14800-356c-11eb-8daa-fd191458a9d1.png)

**Comment by ZEZAY** [comment]
THANK YOU for the report,
The problem has already been sliven.
