### ISSUE TITLE
Functionality Error accessing to the condo page after attached a unit to it

### ISSUE THREAD

**Issue by bleachjade** [ZEZAY/real-estate-rental#32]
After I upload a unit with a negative value, I can not access the condo I attach the unit to it

- http://akezurel.pythonanywhere.com/estate/condo/6/

![image](https://user-images.githubusercontent.com/46812243/100973635-7d9bc500-356d-11eb-94b8-39aa9d285972.png)

This is the information I filled in the unit upload form:

![image](https://user-images.githubusercontent.com/46812243/100973722-a58b2880-356d-11eb-99e5-2883082c6aad.png)
![image](https://user-images.githubusercontent.com/46812243/100973750-b0de5400-356d-11eb-8f7e-97de7afee43c.png)

**Comment by ZEZAY** [comment]
THANK YOU for the report,
The problem has already been sliven.
