### ISSUE TITLE
Can't login will google

### ISSUE THREAD

**Issue by ttxking** [ZEZAY/real-estate-rental#33]
When I tried to login with my Google account , this error is shown:
<img width="1679" alt="Screen Shot 2563-12-03 at 22 08 16" src="https://user-images.githubusercontent.com/59836666/101047493-76e47080-35b4-11eb-964d-0df2c07b42a3.png">

URL : http://akezurel.pythonanywhere.com/accounts/google/login/?process=login

To reproduce :
1. Click login
2. Click Google

**Comment by kaesrel** [comment]
I think I have it fixed now. Please try to login again. 
If it works, please close the issue.
Thank you. 😃

**Comment by ttxking** [comment]
I tested and it works fine!
