### ISSUE TITLE
Can't login with Github

### ISSUE THREAD

**Issue by ttxking** [ZEZAY/real-estate-rental#34]
I tried to log in with Github the page is shown:

<img width="1680" alt="Screen Shot 2563-12-04 at 00 07 56" src="https://user-images.githubusercontent.com/59836666/101063086-fed27680-35c4-11eb-9166-8ec6a4fc8fea.png">

URL : 
http://akezurel.pythonanywhere.com/accounts/github/login/?process=login

Reproduce : 
1. Click login
2. Click login with Github

**Comment by bhatara007** [comment]
> URL :
> http://akezurel.pythonanywhere.com/accounts/github/login/?process=login

Not our URL website?
Check it out here: https://covidtracker-isp.herokuapp.com/

**Comment by kaesrel** [comment]
Same with google login. I have this fixed too.
Please close this issue if it works.

**Comment by ttxking** [comment]
I tested. It works !
