### ISSUE TITLE
DEBUG = True in settings

### ISSUE THREAD

**Issue by ttxking** [ZEZAY/real-estate-rental#35]
Set the DEBUG = True is not good in the production stage, Some of your URLs can be invoked and can cause some problem.

According to Django docs "Never deploy a site into production with DEBUG turned on"
source = https://docs.djangoproject.com/en/dev/ref/settings/#debug

It shown this kind of pages , when the DEBUG is on
<img width="1678" alt="Screen Shot 2563-12-04 at 00 14 42" src="https://user-images.githubusercontent.com/59836666/101063730-bbc4d300-35c5-11eb-8543-8cda0de9acbc.png">

**Comment by Sahadporn** [comment]
Thank you for your report. The issue is fixed.
