### ISSUE TITLE
Unit will negative price is allowed

### ISSUE THREAD

**Issue by ttxking** [ZEZAY/real-estate-rental#36]
The new unit with negative rental and selling price is allowed, this should not be allowed for the real usage

<img width="1678" alt="Screen Shot 2563-12-04 at 00 32 00" src="https://user-images.githubusercontent.com/59836666/101065813-30990c80-35c8-11eb-889d-59cc70270960.png">

URL:http://akezurel.pythonanywhere.com/estate/upload/

Reproduce step :
1. Login
2. Click Post and Add unit
3. Add negative value 
4. Click upload

**Comment by ZEZAY** [comment]
THANK YOU, 
The problem has already been sliven.
